### ISSUE TITLE
fiddler-everywhere 4.0.0  crack

### ISSUE THREAD

**Issue by WangslVIP** [msojocs/fiddler-everywhere-crack#15]
The support for your version of Fiddler Everywhere has come to an end. To access the latest supported version, you will need to complete an update.

Frequent forced updates

**Comment by SelectSex** [comment]
汉化版也给你吧！第一版汉化，有不足之处将就吧，谷歌机翻，介意别用
[Fiddler Everywhere v4.0.0 crack汉化版.zip](https://github.com/msojocs/fiddler-everywhere-crack/files/9982157/Fiddler.Everywhere.v4.0.0.crack.zip)

![image](https://user-images.githubusercontent.com/90268640/201132283-1bdf421f-72ed-4d5a-af61-b84df6b299f7.png)

**Comment by RootEncrypter** [comment]
@SelectSex thank you it works. Could you also send the file to disable automatic updates. And also how to make it in English language. The crack changes it to Chinese language. Thank you

**Comment by SelectSex** [comment]
> @SelectSex谢谢它有效。您能否也发送文件以禁用自动更新。以及如何用英语制作。破解将其更改为中文。谢谢

停止更新的简单方法
去除更新修改js太麻烦的话，还是这样改吧C:\Users\Administrator\AppData\Local\fiddler-everywhere-updater 将这个文件夹删掉 然后新建fiddler-everywhere-updater.txt 文本文件，去除.txt后缀，然后右键设置为属性只读以上操作，Administrator或许需要替换为你的用户名，然后后缀名删除需要打开后缀名显示，然后有些操作需要权限【或许吧】

**Comment by haoirui** [comment]
@SelectSex 一直卡在 please waite。。。

**Comment by RootEncrypter** [comment]
@SelectSex could you please write in steps? I did not understand what you said. I don't understand Chinese. Please tell what to do stepwise , thank you

**Comment by SelectSex** [comment]
C:\Users\Administrator\AppData\Local\fiddler-everywhere-updater 
![image](https://user-images.githubusercontent.com/90268640/201483874-d293962e-33ed-4ad0-ab59-24896909cb55.png)
![image](https://user-images.githubusercontent.com/90268640/201483939-69eac9d3-7592-4fb3-b94b-bfda9ee30558.png)

**Comment by RootEncrypter** [comment]
Thank you

**Comment by WangslVIP** [comment]
> 汉化版也给你吧！第一版汉化，有不足之处将就吧，谷歌机翻，介意别用 [Fiddler Everywhere v4.0.0 crack汉化版.zip](https://github.com/msojocs/fiddler-everywhere-crack/files/9982157/Fiddler.Everywhere.v4.0.0.crack.zip)
> 
> You can have the Chinese version too! The first version of the Chinese, there are shortcomings to make do with it, Google Machine, mind not to use Fiddler Everywhere v4.0.0 crack. Zip
> 
> ![image](https://user-images.githubusercontent.com/90268640/201132283-1bdf421f-72ed-4d5a-af61-b84df6b299f7.png)

感谢大佬，给大佬点赞！英文版和中文汉化版都非常nice
