### ISSUE TITLE
for which version this support?

### ISSUE THREAD

**Issue by TyrellWellick6** [msojocs/fiddler-everywhere-crack#2]
can you please update this out 
and please explain in breif how to apply this 
I hope you will answer me out 
and try to help me out 

谢谢你
thank you

**Comment by msojocs** [comment]
just copy and override files to the path where fiddler everywhere installed,
and I just tested the fiddler everywhere with version `3.2.0`.

**Comment by TyrellWellick6** [comment]
> just copy and override files to the path where fiddler everywhere installed, and I just tested the fiddler everywhere with version `3.2.0`.

where to downlord fiddler 3.2.0

**Comment by msojocs** [comment]
sorry, I can't provide.
you can try to follow the steps in the content of this link (https://www.jysafe.cn/4785.air).
maybe you need to translate the article.

**Comment by TyrellWellick6** [comment]
> sorry, I can't provide. you can try to follow the steps in the content of this link (https://www.jysafe.cn/4785.air). maybe you need to translate the article.

okay sir 
thank you for the help 
any social media account where we can talk ?

**Comment by zju-ch** [comment]
3.2.1 also supported

**Comment by timepandaeric** [comment]
3.3.0 also supported
